### PR TITLE
[Ember] Adjust `rootElement`

### LINKED ISSUE #39: [Ember] different root element
I have quite a few failing tests after applying the codemod, for tests that were using the `:first-child` selector. This is due to the fact that in normal Ember tests the first child will be the component under test, while here it is another wrapper element inside `#ember-testing`. This is similar to the same issue in `ember-native-dom-helpers`: https://github.com/cibernox/ember-native-dom-helpers/issues/63.

I used [this](https://github.com/kaliber5/ember-bootstrap/blob/master/tests/test-helper.js#L16) to fix it for my use, the same selector could be used in your vendor script. Can submit a PR if you agree!?

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #39

### CODE REVIEW

File: tests/acceptance/qunit-dom-test.js [hunk 1]
```diff
@@ -9,10 +9,10 @@ test('qunit-dom assertions are available', function(assert) {
   assert.ok(assert.dom, 'assert.dom is available');
   assert.ok(assert.dom('.foo').includesText, 'assert.dom(...).includesText is available');
 
-  assert.dom('#qunit').doesNotExist('rootElement is set to #ember-testing-container');
-
   visit('/');
   andThen(() => {
+    assert.dom('#qunit').doesNotExist('rootElement is set to #ember-testing-container');
```
Comment (simonihmig) [inline tests/acceptance/qunit-dom-test.js]: Had to move this, because the `.ember-view` seems to be rendered after the `visit` call. Before that `document.querySelector('#ember-testing > .ember-view')` will return `null`...

**Comment by simonihmig** [comment]
Fyi, https://github.com/cibernox/ember-native-dom-helpers/pull/121 has been merged...

File: vendor/overwrite-qunit-dom-root-element.js [hunk 2]
```diff
@@ -1,6 +1,6 @@
 Object.defineProperty(QUnit.assert.dom, 'rootElement', {
   get: function() {
-    return document.querySelector('#ember-testing');
+    return document.querySelector('#ember-testing > .ember-view');
```
Comment (Turbo87) [inline vendor/overwrite-qunit-dom-root-element.js]: Can we make this fallback to the old behavior if the new one can't be found?

File: tests/acceptance/qunit-dom-test.js (hunk 1 above)
Comment (Turbo87) [reply tests/acceptance/qunit-dom-test.js]: Shouldn't be needed with the proposal below.

File: vendor/overwrite-qunit-dom-root-element.js (hunk 2 above)
Comment (simonihmig) [reply vendor/overwrite-qunit-dom-root-element.js]: You mean something like `return document.querySelector('#ember-testing > .ember-view') || document.querySelector('#ember-testing')`?

Comment (Turbo87) [reply vendor/overwrite-qunit-dom-root-element.js]: yep, exactly

Comment (simonihmig) [reply vendor/overwrite-qunit-dom-root-element.js]: Done! Also reverted the changes in the other test, as suggested!

**Comment by Turbo87** [comment]
Thanks! 👍

**Comment by simonihmig** [comment]
Thanks for merging! Would you be able to cut a release with this? Would like to integrate this into ember-bootstrap, where I had some problems because of this issue...

**Comment by Turbo87** [comment]
yep, just published `v0.4.0`
